package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedReportConsSalesPerAlbum generated by hbm2java
 */
public class GeneratedReportConsSalesPerAlbum  implements java.io.Serializable {

    // Fields    

     private String eventName;
     private String albumName;
     private Long albumId;
     private Integer prod10_er;
     private Integer prod11_er;
     private Integer prod13_er;
     private Integer prod20_er;
     private Integer prod30x45;
     private Integer prod40x60;
     private Integer prod50x75;
     private Integer prodMousepad;
     private Integer totalPhotosOrdered;
     private Integer totalOrdersPerAlbum;
     private Integer totalSalesChfPerAlbum;
     private Integer avgPhotosPerOrder;
     private Integer avgSaleChfPerOrder;


    // Constructors

    /** default constructor */
    public GeneratedReportConsSalesPerAlbum() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * 
     */
    public String getAlbumName() {
        return this.albumName;
    }
    
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    /**
     * 
     */
    public Long getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * 
     */
    public Integer getProd10_er() {
        return this.prod10_er;
    }
    
    public void setProd10_er(Integer prod10_er) {
        this.prod10_er = prod10_er;
    }

    /**
     * 
     */
    public Integer getProd11_er() {
        return this.prod11_er;
    }
    
    public void setProd11_er(Integer prod11_er) {
        this.prod11_er = prod11_er;
    }

    /**
     * 
     */
    public Integer getProd13_er() {
        return this.prod13_er;
    }
    
    public void setProd13_er(Integer prod13_er) {
        this.prod13_er = prod13_er;
    }

    /**
     * 
     */
    public Integer getProd20_er() {
        return this.prod20_er;
    }
    
    public void setProd20_er(Integer prod20_er) {
        this.prod20_er = prod20_er;
    }

    /**
     * 
     */
    public Integer getProd30x45() {
        return this.prod30x45;
    }
    
    public void setProd30x45(Integer prod30x45) {
        this.prod30x45 = prod30x45;
    }

    /**
     * 
     */
    public Integer getProd40x60() {
        return this.prod40x60;
    }
    
    public void setProd40x60(Integer prod40x60) {
        this.prod40x60 = prod40x60;
    }

    /**
     * 
     */
    public Integer getProd50x75() {
        return this.prod50x75;
    }
    
    public void setProd50x75(Integer prod50x75) {
        this.prod50x75 = prod50x75;
    }

    /**
     * 
     */
    public Integer getProdMousepad() {
        return this.prodMousepad;
    }
    
    public void setProdMousepad(Integer prodMousepad) {
        this.prodMousepad = prodMousepad;
    }

    /**
     * 
     */
    public Integer getTotalPhotosOrdered() {
        return this.totalPhotosOrdered;
    }
    
    public void setTotalPhotosOrdered(Integer totalPhotosOrdered) {
        this.totalPhotosOrdered = totalPhotosOrdered;
    }

    /**
     * 
     */
    public Integer getTotalOrdersPerAlbum() {
        return this.totalOrdersPerAlbum;
    }
    
    public void setTotalOrdersPerAlbum(Integer totalOrdersPerAlbum) {
        this.totalOrdersPerAlbum = totalOrdersPerAlbum;
    }

    /**
     * 
     */
    public Integer getTotalSalesChfPerAlbum() {
        return this.totalSalesChfPerAlbum;
    }
    
    public void setTotalSalesChfPerAlbum(Integer totalSalesChfPerAlbum) {
        this.totalSalesChfPerAlbum = totalSalesChfPerAlbum;
    }

    /**
     * 
     */
    public Integer getAvgPhotosPerOrder() {
        return this.avgPhotosPerOrder;
    }
    
    public void setAvgPhotosPerOrder(Integer avgPhotosPerOrder) {
        this.avgPhotosPerOrder = avgPhotosPerOrder;
    }

    /**
     * 
     */
    public Integer getAvgSaleChfPerOrder() {
        return this.avgSaleChfPerOrder;
    }
    
    public void setAvgSaleChfPerOrder(Integer avgSaleChfPerOrder) {
        this.avgSaleChfPerOrder = avgSaleChfPerOrder;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("eventName").append("='").append(getEventName()).append("' ");			
      buffer.append("albumName").append("='").append(getAlbumName()).append("' ");			
      buffer.append("albumId").append("='").append(getAlbumId()).append("' ");			
      buffer.append("prod10_er").append("='").append(getProd10_er()).append("' ");			
      buffer.append("prod11_er").append("='").append(getProd11_er()).append("' ");			
      buffer.append("prod13_er").append("='").append(getProd13_er()).append("' ");			
      buffer.append("prod20_er").append("='").append(getProd20_er()).append("' ");			
      buffer.append("prod30x45").append("='").append(getProd30x45()).append("' ");			
      buffer.append("prod40x60").append("='").append(getProd40x60()).append("' ");			
      buffer.append("prod50x75").append("='").append(getProd50x75()).append("' ");			
      buffer.append("prodMousepad").append("='").append(getProdMousepad()).append("' ");			
      buffer.append("totalPhotosOrdered").append("='").append(getTotalPhotosOrdered()).append("' ");			
      buffer.append("totalOrdersPerAlbum").append("='").append(getTotalOrdersPerAlbum()).append("' ");			
      buffer.append("totalSalesChfPerAlbum").append("='").append(getTotalSalesChfPerAlbum()).append("' ");			
      buffer.append("avgPhotosPerOrder").append("='").append(getAvgPhotosPerOrder()).append("' ");			
      buffer.append("avgSaleChfPerOrder").append("='").append(getAvgSaleChfPerOrder()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}