package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedEventGroup generated by hbm2java
 */
public abstract class GeneratedEventGroup extends ch.unartig.studioserver.model.GenericLevel implements java.io.Serializable {

    // Fields    

     private Category category;
     private Set events;


    // Constructors

    /** default constructor */
    public GeneratedEventGroup() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * 
     */
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("category").append("='").append(getCategory()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}