package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedEvent generated by hbm2java
 */
public abstract class GeneratedEvent extends ch.unartig.studioserver.model.GenericLevel implements java.io.Serializable {

    // Fields    

     private Date eventDate;
     private EventGroup eventGroup;
     private Set studios;


    // Constructors

    /** default constructor */
    public GeneratedEvent() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * 
     */
    public EventGroup getEventGroup() {
        return this.eventGroup;
    }
    
    public void setEventGroup(EventGroup eventGroup) {
        this.eventGroup = eventGroup;
    }

    /**
     * 
     */
    public Set getStudios() {
        return this.studios;
    }
    
    public void setStudios(Set studios) {
        this.studios = studios;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("eventGroup").append("='").append(getEventGroup()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}