package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedPriceSegment generated by hbm2java
 */
public class GeneratedPriceSegment  implements java.io.Serializable {

    // Fields    

     private Long priceSegmentId;
     private String priceSegmentName;
     private String oipsProductGroup;


    // Constructors

    /** default constructor */
    public GeneratedPriceSegment() {
    }
    
    /** constructor with id */
    public GeneratedPriceSegment(Long priceSegmentId) {
        this.priceSegmentId = priceSegmentId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getPriceSegmentId() {
        return this.priceSegmentId;
    }
    
    public void setPriceSegmentId(Long priceSegmentId) {
        this.priceSegmentId = priceSegmentId;
    }

    /**
     * 
     */
    public String getPriceSegmentName() {
        return this.priceSegmentName;
    }
    
    public void setPriceSegmentName(String priceSegmentName) {
        this.priceSegmentName = priceSegmentName;
    }

    /**
     * 
     */
    public String getOipsProductGroup() {
        return this.oipsProductGroup;
    }
    
    public void setOipsProductGroup(String oipsProductGroup) {
        this.oipsProductGroup = oipsProductGroup;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("priceSegmentId").append("='").append(getPriceSegmentId()).append("' ");			
      buffer.append("priceSegmentName").append("='").append(getPriceSegmentName()).append("' ");			
      buffer.append("oipsProductGroup").append("='").append(getOipsProductGroup()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}