package ch.unartig.studioserver.model;


/**
 * GeneratedOrderItem generated by hbm2java
 */
public class GeneratedOrderItem  implements java.io.Serializable {

    // Fields    

     private Long orderItemId;
     private Integer quantity;
     private String photoFileName;
     private Photo photo;
     private Product product;
     private Order order;


    // Constructors

    /** default constructor */
    public GeneratedOrderItem() {
    }
    
    /** constructor with id */
    public GeneratedOrderItem(Long orderItemId) {
        this.orderItemId = orderItemId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * 
     */
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * 
     */
    public String getPhotoFileName() {
        return this.photoFileName;
    }
    
    public void setPhotoFileName(String photoFileName) {
        this.photoFileName = photoFileName;
    }

    /**
     * 
     */
    public Photo getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Photo photo) {
        this.photo = photo;
    }

    /**
     * 
     */
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * 
     */
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("orderItemId").append("='").append(getOrderItemId()).append("' ");			
      buffer.append("quantity").append("='").append(getQuantity()).append("' ");			
      buffer.append("photoFileName").append("='").append(getPhotoFileName()).append("' ");			
      buffer.append("photo").append("='").append(getPhoto()).append("' ");			
      buffer.append("product").append("='").append(getProduct()).append("' ");			
      buffer.append("order").append("='").append(getOrder()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}