package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedOrder generated by hbm2java
 */
public class GeneratedOrder  implements java.io.Serializable {

    // Fields    

     private Long orderId;
     private Date orderDate;
     private Date uploadCompletedDate;
     private String oipsOrderId;
     private Customer customer;
     private Set orderItems;


    // Constructors

    /** default constructor */
    public GeneratedOrder() {
    }
    
    /** constructor with id */
    public GeneratedOrder(Long orderId) {
        this.orderId = orderId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * 
     */
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * 
     */
    public Date getUploadCompletedDate() {
        return this.uploadCompletedDate;
    }
    
    public void setUploadCompletedDate(Date uploadCompletedDate) {
        this.uploadCompletedDate = uploadCompletedDate;
    }

    /**
     * 
     */
    public String getOipsOrderId() {
        return this.oipsOrderId;
    }
    
    public void setOipsOrderId(String oipsOrderId) {
        this.oipsOrderId = oipsOrderId;
    }

    /**
     * 
     */
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * 
     */
    public Set getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set orderItems) {
        this.orderItems = orderItems;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("orderId").append("='").append(getOrderId()).append("' ");			
      buffer.append("orderDate").append("='").append(getOrderDate()).append("' ");			
      buffer.append("uploadCompletedDate").append("='").append(getUploadCompletedDate()).append("' ");			
      buffer.append("oipsOrderId").append("='").append(getOipsOrderId()).append("' ");			
      buffer.append("customer").append("='").append(getCustomer()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}