package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedSportsEvent generated by hbm2java
 */
public abstract class GeneratedSportsEvent extends ch.unartig.studioserver.model.Event implements java.io.Serializable {

    // Fields    



    // Constructors

    /** default constructor */
    public GeneratedSportsEvent() {
    }
    
   
    
    

    // Property accessors




}