package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedReportConsSalesPerAlbumDate generated by hbm2java
 */
public class GeneratedReportConsSalesPerAlbumDate  implements java.io.Serializable {

    // Fields    

     private Date date;
     private String eventName;
     private String albumName;
     private Long albumId;
     private Long prod10_er_chf;
     private Long prod10_er_eur;
     private Long prod11_er_chf;
     private Long prod11_er_eur;
     private Long prod13_er_chf;
     private Long prod13_er_eur;
     private Long prod20_er_chf;
     private Long prod20_er_eur;
     private Long prod30x45_chf;
     private Long prod30x45_eur;
     private Long prod40x60_chf;
     private Long prod40x60_eur;
     private Long prod50x75_chf;
     private Long prod50x75_eur;
     private Long prodMousepad_chf;
     private Long prodMousepad_eur;
     private Long prodDigiFoto_chf;
     private Long prodDigiFoto_eur;
     private Long prodDigitalNegative_chf;
     private Long prodDigitalNegative_eur;
     private Long totalPhotosOrdered_chf;
     private Long totalPhotosOrdered_eur;
     private Long totalOrdersPerAlbumDate_chf;
     private Long totalOrdersPerAlbumDate_eur;
     private java.math.BigDecimal totalSalesPerAlbumDate_chf;
     private java.math.BigDecimal totalSalesPerAlbumDate_eur;


    // Constructors

    /** default constructor */
    public GeneratedReportConsSalesPerAlbumDate() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * 
     */
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * 
     */
    public String getAlbumName() {
        return this.albumName;
    }
    
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    /**
     * 
     */
    public Long getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * 
     */
    public Long getProd10_er_chf() {
        return this.prod10_er_chf;
    }
    
    public void setProd10_er_chf(Long prod10_er_chf) {
        this.prod10_er_chf = prod10_er_chf;
    }

    /**
     * 
     */
    public Long getProd10_er_eur() {
        return this.prod10_er_eur;
    }
    
    public void setProd10_er_eur(Long prod10_er_eur) {
        this.prod10_er_eur = prod10_er_eur;
    }

    /**
     * 
     */
    public Long getProd11_er_chf() {
        return this.prod11_er_chf;
    }
    
    public void setProd11_er_chf(Long prod11_er_chf) {
        this.prod11_er_chf = prod11_er_chf;
    }

    /**
     * 
     */
    public Long getProd11_er_eur() {
        return this.prod11_er_eur;
    }
    
    public void setProd11_er_eur(Long prod11_er_eur) {
        this.prod11_er_eur = prod11_er_eur;
    }

    /**
     * 
     */
    public Long getProd13_er_chf() {
        return this.prod13_er_chf;
    }
    
    public void setProd13_er_chf(Long prod13_er_chf) {
        this.prod13_er_chf = prod13_er_chf;
    }

    /**
     * 
     */
    public Long getProd13_er_eur() {
        return this.prod13_er_eur;
    }
    
    public void setProd13_er_eur(Long prod13_er_eur) {
        this.prod13_er_eur = prod13_er_eur;
    }

    /**
     * 
     */
    public Long getProd20_er_chf() {
        return this.prod20_er_chf;
    }
    
    public void setProd20_er_chf(Long prod20_er_chf) {
        this.prod20_er_chf = prod20_er_chf;
    }

    /**
     * 
     */
    public Long getProd20_er_eur() {
        return this.prod20_er_eur;
    }
    
    public void setProd20_er_eur(Long prod20_er_eur) {
        this.prod20_er_eur = prod20_er_eur;
    }

    /**
     * 
     */
    public Long getProd30x45_chf() {
        return this.prod30x45_chf;
    }
    
    public void setProd30x45_chf(Long prod30x45_chf) {
        this.prod30x45_chf = prod30x45_chf;
    }

    /**
     * 
     */
    public Long getProd30x45_eur() {
        return this.prod30x45_eur;
    }
    
    public void setProd30x45_eur(Long prod30x45_eur) {
        this.prod30x45_eur = prod30x45_eur;
    }

    /**
     * 
     */
    public Long getProd40x60_chf() {
        return this.prod40x60_chf;
    }
    
    public void setProd40x60_chf(Long prod40x60_chf) {
        this.prod40x60_chf = prod40x60_chf;
    }

    /**
     * 
     */
    public Long getProd40x60_eur() {
        return this.prod40x60_eur;
    }
    
    public void setProd40x60_eur(Long prod40x60_eur) {
        this.prod40x60_eur = prod40x60_eur;
    }

    /**
     * 
     */
    public Long getProd50x75_chf() {
        return this.prod50x75_chf;
    }
    
    public void setProd50x75_chf(Long prod50x75_chf) {
        this.prod50x75_chf = prod50x75_chf;
    }

    /**
     * 
     */
    public Long getProd50x75_eur() {
        return this.prod50x75_eur;
    }
    
    public void setProd50x75_eur(Long prod50x75_eur) {
        this.prod50x75_eur = prod50x75_eur;
    }

    /**
     * 
     */
    public Long getProdMousepad_chf() {
        return this.prodMousepad_chf;
    }
    
    public void setProdMousepad_chf(Long prodMousepad_chf) {
        this.prodMousepad_chf = prodMousepad_chf;
    }

    /**
     * 
     */
    public Long getProdMousepad_eur() {
        return this.prodMousepad_eur;
    }
    
    public void setProdMousepad_eur(Long prodMousepad_eur) {
        this.prodMousepad_eur = prodMousepad_eur;
    }

    /**
     * 
     */
    public Long getProdDigiFoto_chf() {
        return this.prodDigiFoto_chf;
    }
    
    public void setProdDigiFoto_chf(Long prodDigiFoto_chf) {
        this.prodDigiFoto_chf = prodDigiFoto_chf;
    }

    /**
     * 
     */
    public Long getProdDigiFoto_eur() {
        return this.prodDigiFoto_eur;
    }
    
    public void setProdDigiFoto_eur(Long prodDigiFoto_eur) {
        this.prodDigiFoto_eur = prodDigiFoto_eur;
    }

    /**
     * 
     */
    public Long getProdDigitalNegative_chf() {
        return this.prodDigitalNegative_chf;
    }
    
    public void setProdDigitalNegative_chf(Long prodDigitalNegative_chf) {
        this.prodDigitalNegative_chf = prodDigitalNegative_chf;
    }

    /**
     * 
     */
    public Long getProdDigitalNegative_eur() {
        return this.prodDigitalNegative_eur;
    }
    
    public void setProdDigitalNegative_eur(Long prodDigitalNegative_eur) {
        this.prodDigitalNegative_eur = prodDigitalNegative_eur;
    }

    /**
     * 
     */
    public Long getTotalPhotosOrdered_chf() {
        return this.totalPhotosOrdered_chf;
    }
    
    public void setTotalPhotosOrdered_chf(Long totalPhotosOrdered_chf) {
        this.totalPhotosOrdered_chf = totalPhotosOrdered_chf;
    }

    /**
     * 
     */
    public Long getTotalPhotosOrdered_eur() {
        return this.totalPhotosOrdered_eur;
    }
    
    public void setTotalPhotosOrdered_eur(Long totalPhotosOrdered_eur) {
        this.totalPhotosOrdered_eur = totalPhotosOrdered_eur;
    }

    /**
     * 
     */
    public Long getTotalOrdersPerAlbumDate_chf() {
        return this.totalOrdersPerAlbumDate_chf;
    }
    
    public void setTotalOrdersPerAlbumDate_chf(Long totalOrdersPerAlbumDate_chf) {
        this.totalOrdersPerAlbumDate_chf = totalOrdersPerAlbumDate_chf;
    }

    /**
     * 
     */
    public Long getTotalOrdersPerAlbumDate_eur() {
        return this.totalOrdersPerAlbumDate_eur;
    }
    
    public void setTotalOrdersPerAlbumDate_eur(Long totalOrdersPerAlbumDate_eur) {
        this.totalOrdersPerAlbumDate_eur = totalOrdersPerAlbumDate_eur;
    }

    /**
     * 
     */
    public java.math.BigDecimal getTotalSalesPerAlbumDate_chf() {
        return this.totalSalesPerAlbumDate_chf;
    }
    
    public void setTotalSalesPerAlbumDate_chf(java.math.BigDecimal totalSalesPerAlbumDate_chf) {
        this.totalSalesPerAlbumDate_chf = totalSalesPerAlbumDate_chf;
    }

    /**
     * 
     */
    public java.math.BigDecimal getTotalSalesPerAlbumDate_eur() {
        return this.totalSalesPerAlbumDate_eur;
    }
    
    public void setTotalSalesPerAlbumDate_eur(java.math.BigDecimal totalSalesPerAlbumDate_eur) {
        this.totalSalesPerAlbumDate_eur = totalSalesPerAlbumDate_eur;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("date").append("='").append(getDate()).append("' ");			
      buffer.append("eventName").append("='").append(getEventName()).append("' ");			
      buffer.append("albumName").append("='").append(getAlbumName()).append("' ");			
      buffer.append("albumId").append("='").append(getAlbumId()).append("' ");			
      buffer.append("prod10_er_chf").append("='").append(getProd10_er_chf()).append("' ");			
      buffer.append("prod10_er_eur").append("='").append(getProd10_er_eur()).append("' ");			
      buffer.append("prod11_er_chf").append("='").append(getProd11_er_chf()).append("' ");			
      buffer.append("prod11_er_eur").append("='").append(getProd11_er_eur()).append("' ");			
      buffer.append("prod13_er_chf").append("='").append(getProd13_er_chf()).append("' ");			
      buffer.append("prod13_er_eur").append("='").append(getProd13_er_eur()).append("' ");			
      buffer.append("prod20_er_chf").append("='").append(getProd20_er_chf()).append("' ");			
      buffer.append("prod20_er_eur").append("='").append(getProd20_er_eur()).append("' ");			
      buffer.append("prod30x45_chf").append("='").append(getProd30x45_chf()).append("' ");			
      buffer.append("prod30x45_eur").append("='").append(getProd30x45_eur()).append("' ");			
      buffer.append("prod40x60_chf").append("='").append(getProd40x60_chf()).append("' ");			
      buffer.append("prod40x60_eur").append("='").append(getProd40x60_eur()).append("' ");			
      buffer.append("prod50x75_chf").append("='").append(getProd50x75_chf()).append("' ");			
      buffer.append("prod50x75_eur").append("='").append(getProd50x75_eur()).append("' ");			
      buffer.append("prodMousepad_chf").append("='").append(getProdMousepad_chf()).append("' ");			
      buffer.append("prodMousepad_eur").append("='").append(getProdMousepad_eur()).append("' ");			
      buffer.append("prodDigiFoto_chf").append("='").append(getProdDigiFoto_chf()).append("' ");			
      buffer.append("prodDigiFoto_eur").append("='").append(getProdDigiFoto_eur()).append("' ");			
      buffer.append("prodDigitalNegative_chf").append("='").append(getProdDigitalNegative_chf()).append("' ");			
      buffer.append("prodDigitalNegative_eur").append("='").append(getProdDigitalNegative_eur()).append("' ");			
      buffer.append("totalPhotosOrdered_chf").append("='").append(getTotalPhotosOrdered_chf()).append("' ");			
      buffer.append("totalPhotosOrdered_eur").append("='").append(getTotalPhotosOrdered_eur()).append("' ");			
      buffer.append("totalOrdersPerAlbumDate_chf").append("='").append(getTotalOrdersPerAlbumDate_chf()).append("' ");			
      buffer.append("totalOrdersPerAlbumDate_eur").append("='").append(getTotalOrdersPerAlbumDate_eur()).append("' ");			
      buffer.append("totalSalesPerAlbumDate_chf").append("='").append(getTotalSalesPerAlbumDate_chf()).append("' ");			
      buffer.append("totalSalesPerAlbumDate_eur").append("='").append(getTotalSalesPerAlbumDate_eur()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}