package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedAlbumAdvertisment generated by hbm2java
 */
public class GeneratedAlbumAdvertisment  implements java.io.Serializable {

    // Fields    

     private Long albumAdvertismentId;
     private String position;
     private String adLinkText;
     private GenericLevel album;


    // Constructors

    /** default constructor */
    public GeneratedAlbumAdvertisment() {
    }
    
    /** constructor with id */
    public GeneratedAlbumAdvertisment(Long albumAdvertismentId) {
        this.albumAdvertismentId = albumAdvertismentId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getAlbumAdvertismentId() {
        return this.albumAdvertismentId;
    }
    
    public void setAlbumAdvertismentId(Long albumAdvertismentId) {
        this.albumAdvertismentId = albumAdvertismentId;
    }

    /**
     * 
     */
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * 
     */
    public String getAdLinkText() {
        return this.adLinkText;
    }
    
    public void setAdLinkText(String adLinkText) {
        this.adLinkText = adLinkText;
    }

    /**
     * 
     */
    public GenericLevel getAlbum() {
        return this.album;
    }
    
    public void setAlbum(GenericLevel album) {
        this.album = album;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("albumAdvertismentId").append("='").append(getAlbumAdvertismentId()).append("' ");			
      buffer.append("position").append("='").append(getPosition()).append("' ");			
      buffer.append("adLinkText").append("='").append(getAdLinkText()).append("' ");			
      buffer.append("album").append("='").append(getAlbum()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}