package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedEventRunner generated by hbm2java
 */
public class GeneratedEventRunner  implements java.io.Serializable {

    // Fields    

     private Event event;
     private PhotoSubject photoSubject;
     private String startnumber;
     private Integer rank;
     private String runningTime;


    // Constructors

    /** default constructor */
    public GeneratedEventRunner() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    /**
     * 
     */
    public PhotoSubject getPhotoSubject() {
        return this.photoSubject;
    }
    
    public void setPhotoSubject(PhotoSubject photoSubject) {
        this.photoSubject = photoSubject;
    }

    /**
     * 
     */
    public String getStartnumber() {
        return this.startnumber;
    }
    
    public void setStartnumber(String startnumber) {
        this.startnumber = startnumber;
    }

    /**
     * 
     */
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * 
     */
    public String getRunningTime() {
        return this.runningTime;
    }
    
    public void setRunningTime(String runningTime) {
        this.runningTime = runningTime;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("event").append("='").append(getEvent()).append("' ");			
      buffer.append("photoSubject").append("='").append(getPhotoSubject()).append("' ");			
      buffer.append("startnumber").append("='").append(getStartnumber()).append("' ");			
      buffer.append("rank").append("='").append(getRank()).append("' ");			
      buffer.append("runningTime").append("='").append(getRunningTime()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}