package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedCategory generated by hbm2java
 */
public abstract class GeneratedCategory extends ch.unartig.studioserver.model.GenericLevel implements java.io.Serializable {

    // Fields    

     private Set eventGroups;


    // Constructors

    /** default constructor */
    public GeneratedCategory() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Set getEventGroups() {
        return this.eventGroups;
    }
    
    public void setEventGroups(Set eventGroups) {
        this.eventGroups = eventGroups;
    }




}