package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedSportsAlbum generated by hbm2java
 */
public abstract class GeneratedSportsAlbum extends ch.unartig.studioserver.model.StudioAlbum implements java.io.Serializable {

    // Fields    



    // Constructors

    /** default constructor */
    public GeneratedSportsAlbum() {
    }
    
   
    
    

    // Property accessors




}