package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedPhotoSubject generated by hbm2java
 */
public class GeneratedPhotoSubject  implements java.io.Serializable {

    // Fields    

     private Long photoSubjectId;
     private String name;
     private Integer age;
     private Set photos;
     private Set eventRunners;


    // Constructors

    /** default constructor */
    public GeneratedPhotoSubject() {
    }
    
    /** constructor with id */
    public GeneratedPhotoSubject(Long photoSubjectId) {
        this.photoSubjectId = photoSubjectId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getPhotoSubjectId() {
        return this.photoSubjectId;
    }
    
    public void setPhotoSubjectId(Long photoSubjectId) {
        this.photoSubjectId = photoSubjectId;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * 
     */
    protected Set getPhotos() {
        return this.photos;
    }
    
    protected void setPhotos(Set photos) {
        this.photos = photos;
    }

    /**
     * 
     */
    public Set getEventRunners() {
        return this.eventRunners;
    }
    
    public void setEventRunners(Set eventRunners) {
        this.eventRunners = eventRunners;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("photoSubjectId").append("='").append(getPhotoSubjectId()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("age").append("='").append(getAge()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}