package ch.unartig.studioserver.model;

import java.util.*;




/**
 * GeneratedProduct generated by hbm2java
 */
public class GeneratedProduct  implements java.io.Serializable {

    // Fields    

     private Long productId;
     private String productName;
     private String oipsPid;
     private String oipsName;
     private Integer oipsPriceCHF;
     private Integer oipsPriceEUR;
     private Integer oipsPriceGBP;
     private Integer oipsPriceSEK;
     private Integer oipsWidth;
     private Integer oipsHeight;
     private Boolean oipsVariableLength;
     private Integer oipsGroupId;
     private PriceSegment priceSegment;
     private Price price;
     private ProductType productType;


    // Constructors

    /** default constructor */
    public GeneratedProduct() {
    }
    
    /** constructor with id */
    public GeneratedProduct(Long productId) {
        this.productId = productId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getProductId() {
        return this.productId;
    }
    
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * 
     */
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * 
     */
    public String getOipsPid() {
        return this.oipsPid;
    }
    
    public void setOipsPid(String oipsPid) {
        this.oipsPid = oipsPid;
    }

    /**
     * 
     */
    public String getOipsName() {
        return this.oipsName;
    }
    
    public void setOipsName(String oipsName) {
        this.oipsName = oipsName;
    }

    /**
     * 
     */
    public Integer getOipsPriceCHF() {
        return this.oipsPriceCHF;
    }
    
    public void setOipsPriceCHF(Integer oipsPriceCHF) {
        this.oipsPriceCHF = oipsPriceCHF;
    }

    /**
     * 
     */
    public Integer getOipsPriceEUR() {
        return this.oipsPriceEUR;
    }
    
    public void setOipsPriceEUR(Integer oipsPriceEUR) {
        this.oipsPriceEUR = oipsPriceEUR;
    }

    /**
     * 
     */
    public Integer getOipsPriceGBP() {
        return this.oipsPriceGBP;
    }
    
    public void setOipsPriceGBP(Integer oipsPriceGBP) {
        this.oipsPriceGBP = oipsPriceGBP;
    }

    /**
     * 
     */
    public Integer getOipsPriceSEK() {
        return this.oipsPriceSEK;
    }
    
    public void setOipsPriceSEK(Integer oipsPriceSEK) {
        this.oipsPriceSEK = oipsPriceSEK;
    }

    /**
     * 
     */
    public Integer getOipsWidth() {
        return this.oipsWidth;
    }
    
    public void setOipsWidth(Integer oipsWidth) {
        this.oipsWidth = oipsWidth;
    }

    /**
     * 
     */
    public Integer getOipsHeight() {
        return this.oipsHeight;
    }
    
    public void setOipsHeight(Integer oipsHeight) {
        this.oipsHeight = oipsHeight;
    }

    /**
     * 
     */
    public Boolean getOipsVariableLength() {
        return this.oipsVariableLength;
    }
    
    public void setOipsVariableLength(Boolean oipsVariableLength) {
        this.oipsVariableLength = oipsVariableLength;
    }

    /**
     * 
     */
    public Integer getOipsGroupId() {
        return this.oipsGroupId;
    }
    
    public void setOipsGroupId(Integer oipsGroupId) {
        this.oipsGroupId = oipsGroupId;
    }

    /**
     * 
     */
    public PriceSegment getPriceSegment() {
        return this.priceSegment;
    }
    
    public void setPriceSegment(PriceSegment priceSegment) {
        this.priceSegment = priceSegment;
    }

    /**
     * 
     */
    public Price getPrice() {
        return this.price;
    }
    
    public void setPrice(Price price) {
        this.price = price;
    }

    /**
     * 
     */
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }

  /**
	 * toString
	 * @return String
	 */
  public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("productId").append("='").append(getProductId()).append("' ");			
      buffer.append("productName").append("='").append(getProductName()).append("' ");			
      buffer.append("oipsPid").append("='").append(getOipsPid()).append("' ");			
      buffer.append("oipsName").append("='").append(getOipsName()).append("' ");			
      buffer.append("oipsPriceCHF").append("='").append(getOipsPriceCHF()).append("' ");			
      buffer.append("oipsPriceEUR").append("='").append(getOipsPriceEUR()).append("' ");			
      buffer.append("oipsPriceGBP").append("='").append(getOipsPriceGBP()).append("' ");			
      buffer.append("oipsPriceSEK").append("='").append(getOipsPriceSEK()).append("' ");			
      buffer.append("oipsWidth").append("='").append(getOipsWidth()).append("' ");			
      buffer.append("oipsHeight").append("='").append(getOipsHeight()).append("' ");			
      buffer.append("oipsVariableLength").append("='").append(getOipsVariableLength()).append("' ");			
      buffer.append("oipsGroupId").append("='").append(getOipsGroupId()).append("' ");			
      buffer.append("priceSegment").append("='").append(getPriceSegment()).append("' ");			
      buffer.append("price").append("='").append(getPrice()).append("' ");			
      buffer.append("productType").append("='").append(getProductType()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
	}



}